version: '3.8'

networks:
  jano-net:
    driver: bridge


volumes:
  redis_data:
  es_data:


services:

  # 1. Redis Service
  redis:
    image: redis:latest
    container_name: jano-redis-app
    restart: always                                                   # Always restart if crash or manually stop
    ports:
      - "6379:6379"
    networks:
      - jano-net
    volumes:
      - redis_data:/data
    healthcheck:                                                      # Check if avaiable container
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: jano-es-app
    restart: unless-stopped                                           # Auto restart if crash but not manually stop
    environment:  
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - jano-net
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:                                                          # Increase the memory limit for JAVA
      memlock:
        soft: -1
        hard: -1

  # 3. Worker Service 
  jano-worker:
    image: tannguyen012/jano-flask-app:v1.1.0
    deploy:
      replicas: 4                                                     # Run 4 worker (Message Queue)
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=host.docker.internal
      - ES_URL=http://jano-es-app:9200
      - REDIS_URL=redis://jano-redis-app:6379
      - FULL_JOB_INTERVAL=60
    extra_hosts:
      - "host.docker.internal:host-gateway"                                         
    networks:
      - jano-net
    depends_on:
      redis:
        condition: service_healthy                                    # Worker only run if redis container is ready
      elasticsearch:
        condition: service_started
                                                                      # Override command and run this command when start container
    command: celery -A worker.celery worker --loglevel=info --pool=solo --hostname=worker@%h     


  # 4. Flask Service
  flask-app:
    image: tannguyen012/jano-flask-app:v1.1.0                         # Change version if push new image 
    container_name: jano-flask-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=host.docker.internal
      - ES_URL=http://jano-es-app:9200
      - REDIS_URL=redis://jano-redis-app:6379
      - FULL_JOB_INTERVAL=300
      - PROFILE_JOB_INTERVAL=360
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jano-net
    depends_on:
      - redis
      - elasticsearch

  # 5. Node Service
  node-app:
    image: tannguyen012/jano-node-app:v1.1.0                           # Change version if push new image 
    container_name: jano-node-app
    restart: always
    ports: 
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://admin:webblogpassword@host.docker.internal:3307/web_blog_db
      - PYTHON_API=http://jano-flask-app:5000
      - REDIS_URL=redis://jano-redis-app:6379
      - FRONTEND_URL=http://52.74.243.85:5173                          # Public IP of VM
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - jano-net
    depends_on:
      - flask-app
      - redis


  # 6. React Service
  react-app:
    image: tannguyen012/jano-react-app:v1.1.0                          # Change version if push new image 
    container_name: jano-react-app
    restart: always
    ports:
      - "5173:80"
    networks:
      - jano-net
